# -*- coding: utf-8 -*-
"""mav

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189GXYTGjpGuSLHD5Zn9XoF6TugUl1z9-
"""

# Definindo os valores da matriz de confusão de forma arbitrária
# VP: Verdadeiros Positivos
# VN: Verdadeiros Negativos
# FP: Falsos Positivos
# FN: Falsos Negativos
VP = 50
VN = 100
FP = 10
FN = 5

print("Valores da Matriz de Confusão:")
print(f"Verdadeiros Positivos (VP): {VP}")
print(f"Verdadeiros Negativos (VN): {VN}")
print(f"Falsos Positivos (FP): {FP}")
print(f"Falsos Negativos (FN): {FN}\n")

def calcular_acuracia(vp, vn, fp, fn):
    """
    Calcula a acurácia do modelo de classificação.
    Acurácia: (VP + VN) / (VP + VN + FP + FN)
    """
    total = vp + vn + fp + fn
    if total == 0:
        return 0.0
    acuracia = (vp + vn) / total
    return acuracia

def calcular_sensibilidade(vp, fn):
    """
    Calcula a sensibilidade (recall) do modelo.
    Sensibilidade: VP / (VP + FN)
    """
    if (vp + fn) == 0:
        return 0.0
    sensibilidade = vp / (vp + fn)
    return sensibilidade

def calcular_especificidade(vn, fp):
    """
    Calcula a especificidade do modelo.
    Especificidade: VN / (VN + FP)
    """
    if (vn + fp) == 0:
        return 0.0
    especificidade = vn / (vn + fp)
    return especificidade

def calcular_precisao(vp, fp):
    """
    Calcula a precisão do modelo.
    Precisão: VP / (VP + FP)
    """
    if (vp + fp) == 0:
        return 0.0
    precisao = vp / (vp + fp)
    return precisao

def calcular_f1_score(precisao, sensibilidade):
    """
    Calcula o F-score (F1-score) do modelo.
    F1-score: 2 * ((Precisão * Sensibilidade) / (Precisão + Sensibilidade))
    """
    if (precisao + sensibilidade) == 0:
        return 0.0
    f1_score = 2 * ((precisao * sensibilidade) / (precisao + sensibilidade))
    return f1_score

# --- Execução dos Cálculos ---

# 1. Calcular Acurácia
acuracia = calcular_acuracia(VP, VN, FP, FN)

# 2. Calcular Sensibilidade e Precisão (necessárias para o F-score)
sensibilidade = calcular_sensibilidade(VP, FN)
precisao = calcular_precisao(VP, FP)

# 3. Calcular Especificidade
especificidade = calcular_especificidade(VN, FP)

# 4. Calcular F-score
f1_score = calcular_f1_score(precisao, sensibilidade)

# --- Exibição dos Resultados ---
print("--- Métricas de Avaliação ---")
print(f"Acurácia: {acuracia:.4f}")
print(f"Sensibilidade (Recall): {sensibilidade:.4f}")
print(f"Especificidade: {especificidade:.4f}")
print(f"Precisão: {precisao:.4f}")
print(f"F-score (F1-score): {f1_score:.4f}")